steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/chessbook/404210/chessbook/frontend:latest', '.']
  automapSubstitutions: true

# Add the step for pushing the Docker image to GCR
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/chessbook/404210/chessbook/frontend:latest']

# Authenticate with the GKE cluster
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud container clusters get-credentials $CLUSTER_NAME --zone $_CLUSTER_ZONE --project $_PROJECT_ID
      kubectl rollout restart deployment chess

images:
- 'us-central1-docker.pkg.dev/chessbook/404210/chessbook/frontend:latest'

substitutions:
  _CLUSTER_NAME: 'chessbook-cluster' # replace with your actual cluster name
  _CLUSTER_ZONE: 'us-east1' # replace with your actual cluster zone
  _PROJECT_ID: 'chessbook-404210' # replace with your actual project ID
