apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-frontend
spec:
  selector:
    matchLabels:
      app: chess-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: chess-frontend
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/chessbook-404210/chessbook/frontend:latest
          imagePullPolicy: Always
          name: chess-frontend
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 2
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: chess-frontend
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: chess-frontend
