apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-frontend
spec:
  selector:
    matchLabels:
      app: chess-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: chess-frontend
    spec:
      containers:
        - image: marcusbuffett/chess-frontend:latest
          name: chess-frontend
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 2
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
      imagePullSecrets:
        - name: docker-hub-secret-key
---
apiVersion: v1
kind: Service
metadata:
  name: chess-frontend
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: chess-frontend
  type: NodePort
